language: python
python:
  - "2.7"
before_install:
  - export PIP_USE_MIRRORS=true
  - export PIP_INDEX_URL=https://simple.crate.io/
  - export DJANGO_SETTINGS_MODULE=tests.settings
install:
  - pip install https://github.com/django/django/archive/${DJANGO}.zip#egg=django
  - pip install -r tests.pip
  - pip install -e .
script:
  - py.test tests/
env:
  - DJANGO=1.4.3
  - DJANGO=1.5c1
